### ISSUE TITLE
Chapter 07 - Error

### ISSUE THREAD

**Issue by oscarjb1** [PacktPublishing/Mastering-Spring-Boot-2.0#4]
Hi, I get the following error when executing the project "api-zuul-service":

`***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method ribbonCommandFactory in org.springframework.cloud.netflix.zuul.RibbonCommandFactoryConfiguration$HttpClientRibbonConfiguration required a bean of type 'org.springframework.cloud.netflix.ribbon.SpringClientFactory' that could not be found.
	- Bean method 'springClientFactory' not loaded because @ConditionalOnClass did not find required class 'com.netflix.client.IClient'

Action:

Consider revisiting the conditions above or defining a bean of type 'org.springframework.cloud.netflix.ribbon.SpringClientFactory' in your configuration.`

**Comment by oscarjb1** [comment]
there is no support?

**Comment by dineshonjava** [comment]
Please check the pom file. This issue related to the libraries missing. And also, you can change the Spring Boot version with the current one.
